# Generated by Django 4.1 on 2022-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermsg',
            name='chatstatus',
            field=models.BooleanField(default=False),
        ),
    ]
